# Generated by Django 5.0.1 on 2024-03-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_type', models.CharField(choices=[('patient', 'PATIENT'), ('doctor', 'DOCTOR')], max_length=30, null=True)),
                ('message', models.CharField(max_length=250, null=True)),
                ('notification_type', models.CharField(choices=[('booked', 'New Booked'), ('pending', 'New Pending'), ('completed', 'New Completed'), ('cancelled', 'New Cancelled')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to='account.doctor')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to='account.patient')),
            ],
        ),
    ]
