# Generated by Django 5.0.1 on 2024-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID'),
        ),
    ]
